### ISSUE TITLE
Twitter repository version

### ISSUE THREAD

**Issue by rduffield** [twitter-archive/cassie#10]
Is it possible to add 0.24.0 to the Twitter repository at http://maven.twttr.com/?  The most recent version in the repository is 0.20.0.

**Comment by boazavital** [comment]
We've stopped publishing the parent pom, but the most recent version of
cassie-core and friends in maven is 0.25.3:
http://maven.twttr.com/com/twitter/cassie-core/

**Comment by rduffield** [comment]
Perfect, thank you.
