### ISSUE TITLE
Wiki hijacked?

### ISSUE THREAD

**Issue by ghost** [twitter-archive/cassie#7]
I don't think this belongs there: https://github.com/twitter/cassie/wiki
![Screenshot](https://f.cloud.github.com/assets/4346811/463693/e47584fc-b58f-11e2-9e49-337d14ac6717.png)

**Comment by caniszczyk** [comment]
Thanks, fixed.

Also restricted wiki edit access to folks with push access.

**Comment by ghost** [comment]
Wow, fixed within one minute. Nice! ;)
